enabled: true
production: false
append_site_title: true
custom_logo_strip_svg_style: false
colors:
  text_style: 'text-gray-600 dark:text-gray-400'
  brightness_lighter: 10
  brightness_darker: 10
  primary: '#00a0de'
appearance:
  theme: dark
  selector: true
  storage: true
section_classes: 'bg-white dark:bg-gray-900 py-8 md:py-24'
wrapper_spacing: 'xl:container xl:mx-auto md:px-6 px-4'
header_bar:
  logo: default
  background: auto
  text: auto
  primary_menu_levels: 3
  custom_style: 'linear-gradient(90deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.4) 100%)'
hero:
  display: true
  overlay: dark
  overlay_direction: right
  alignment: left
  image: 'theme://images/headers/sea-and-sky.jpg'
  custom: '#3C4043'
  padding: 'pt-32 md:pt-40 lg:pt-48 xl:pt-56 pb-16 md:pb-20 lg:pb-24 xl:pb-32'
  overlay_gradient:
    - '0.8'
    - '0.3'
footer:
  menu:
    -
      label: 'Terms & Conditions'
      link: '#'
    -
      label: 'Privacy Policy'
      link: '#'
  social:
    -
      network: twitter
      link: 'https://twitter.com/getgrav'
    -
      network: github
      link: 'https://github.com/getgrav'
  copyright: "[Grav](https://getgrav.org?classes=hover:text-primary,font-bold) was \r\n[svg-icon icon=\"code\" class=\"text-gray-700 dark:text-gray-400 w-4 h-4\"] with\r\n[svg-icon icon=\"heart\" class=\"text-red-700 w-4 h-4 animate-pulse\"] by \r\n[Trilby Media, LLC](https://trilby.media?classes=hover:text-primary,font-bold)\r\n"
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/mytheme, user/themes/typhoon]
custom_logo: {  }
